name: "pages"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Github Pages deploy
      uses: skywarth/vite-github-pages-deployer@v1.5.0
          
